<a href="https://colab.research.google.com/github/jtmeawno1/BasicProg_DataViz65/blob/main/Quiz_Group_5_20_of_Midterm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [71]:
from google.colab import drive 
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [72]:
import pandas as pd

# ความกด

## เลย

In [73]:
pressure_lei = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ความกด(เปอร์เซ็นต์)/จ.เลย.xlsx',skiprows=3).drop(0, axis=0)
pressure_lei.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
pressure_lei['จังหวัด'] = 'เลย'
pressure_lei['เดือน'] =pressure_lei['เดือน/ปี'].dt.month
pressure_lei['ปี'] = pressure_lei['เดือน/ปี'].dt.year
pres_lei = pressure_lei[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]
pres_lei.head(3)

,จังหวัด,สถานี,เดือน,ปี,1,2,3,4,5,6,...,22,23,24,25,26,27,28,29,30,31
1,เลย,352201-หนองคาย จ.หนองคาย,10,2011,1005.12,1006.51,1007.81,1008.15,1009.21,1011.28,...,1010.98,1010.79,1010.25,1011.52,1012.04,1012.00,1012.74,1011.69,1011.27,1011.71
2,เลย,352201-หนองคาย จ.หนองคาย,11,2011,1012.09,1011.32,1010.99,1011.47,1010.88,1009.62,...,1014.21,1014.79,1015.74,1014.36,1013.30,1011.92,1009.86,1010.1,1010.43,-
3,เลย,352201-หนองคาย จ.หนองคาย,12,2011,1010.43,1011.81,1012.45,1012.03,1013.29,1013.21,...,1014.34,1013.75,1013.11,1015.95,1018.79,1019.39,1017.88,1016.49,1014.97,1015.62

## สกลนคร

In [74]:
pressure_snk = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ความกด(เปอร์เซ็นต์)/จ.สกลนคร.xlsx',skiprows=3).drop(0, axis=0)
pressure_snk.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
pressure_snk['จังหวัด'] = 'สกลนคร'
pressure_snk['เดือน'] = pressure_snk['เดือน/ปี'].dt.month
pressure_snk['ปี'] = pressure_snk['เดือน/ปี'].dt.year
pres_snk = pressure_snk[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## นครพนม

In [75]:
pressure_npm = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ความกด(เปอร์เซ็นต์)/จ.นครพนม.xlsx',skiprows=3).drop(0, axis=0)
pressure_npm.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
pressure_npm['จังหวัด'] = 'นครพนม'
pressure_npm['เดือน'] = pressure_npm['เดือน/ปี'].dt.month
pressure_npm['ปี'] = pressure_npm['เดือน/ปี'].dt.year
pres_npm = pressure_npm[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## หนองคาย

In [76]:
pressure_nki = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ความกด(เปอร์เซ็นต์)/จ.หนองคาย.xlsx',skiprows=3).drop(0, axis=0)
pressure_nki.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
pressure_nki['จังหวัด'] = 'หนองคาย'
pressure_nki['เดือน'] = pressure_nki['เดือน/ปี'].dt.month
pressure_nki['ปี'] = pressure_nki['เดือน/ปี'].dt.year
pres_nk = pressure_nki[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## ขอนแก่น

In [77]:
pressure_kkn = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ความกด(เปอร์เซ็นต์)/จ.ขอนแก่น.xlsx',skiprows=3).drop(0, axis=0)
pressure_kkn.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
pressure_kkn['จังหวัด'] = 'ขอนแก่น'
pressure_kkn['เดือน'] = pressure_kkn['เดือน/ปี'].dt.month 
pressure_kkn['ปี'] = pressure_kkn['เดือน/ปี'].dt.year 
pres_kn = pressure_kkn[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## รวมตารางความกด ทั้ง 5 จังหวัด

In [78]:
all_province = pd.concat([pres_lei, pres_snk, pres_npm, pres_nk, pres_kn])
all_province

,จังหวัด,สถานี,เดือน,ปี,1,2,3,4,5,6,...,22,23,24,25,26,27,28,29,30,31
1,เลย,352201-หนองคาย จ.หนองคาย,10,2011,1005.12,1006.51,1007.81,1008.15,1009.21,1011.28,...,1010.98,1010.79,1010.25,1011.52,1012.04,1012.00,1012.74,1011.69,1011.27,1011.71
2,เลย,352201-หนองคาย จ.หนองคาย,11,2011,1012.09,1011.32,1010.99,1011.47,1010.88,1009.62,...,1014.21,1014.79,1015.74,1014.36,1013.30,1011.92,1009.86,1010.1,1010.43,-
3,เลย,352201-หนองคาย จ.หนองคาย,12,2011,1010.43,1011.81,1012.45,1012.03,1013.29,1013.21,...,1014.34,1013.75,1013.11,1015.95,1018.79,1019.39,1017.88,1016.49,1014.97,1015.62
4,เลย,352201-หนองคาย จ.หนองคาย,1,2012,1015.42,1014.07,1012.35,1013.49,1014.99,1015.70,...,1009.65,1010.10,1010.76,1011.11,1011.72,1010.91,1010.31,1010.16,1012.61,1014.4
5,เลย,352201-หนองคาย จ.หนองคาย,2,2012,1013.19,1012.82,1013.94,1013.18,1010.99,1008.58,...,1006.79,1005.78,1005.48,1004.96,1005.05,1006.27,1005.59,1006.52,1010.43,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,ขอนแก่น,352201-หนองคาย จ.หนองคาย,10,2021,1008.12,1008.74,1008.64,1008.16,1007.42,1005.93,...,1013.04,1015.21,1015.08,1013.52,1012.33,1012.16,1012.33,1013.04,1013.26,1012.96
52,ขอนแก่น,352201-หนองคาย จ.หนองคาย,11,2021,1013.23,1013.04,1012.50,1011.41,1009.71,1007.97,...,1011.00,1013.18,1014.70,1014.53,1014.41,1015.51,1014.45,1013.37,1013.98,-
53,ขอนแก่น,352201-หนองคาย จ.หนองคาย,12,2021,1015.80,1017.00,1018.68,1018.13,1017.43,1016.91,...,1013.32,1012.63,1012.30,1013.87,1015.64,1017.06,1017.58,1016.4,1017.83,1018.39
54,ขอนแก่น,352201-หนองคาย จ.หนองคาย,1,2022,1017.75,1016.89,1015.26,1014.98,1013.66,1014.12,...,1010.49,1010.66,1010.19,1010.22,1010.70,1010.80,1010.52,1008.55,1007.99,1008.91
55,ขอนแก่น,352201-หนองคาย จ.หนองคาย,2,2022,1010.90,1012.02,1012.12,1013.77,1015.52,1014.63,...,1016.38,1017.55,1019.04,1018.41,1016.05,1014.37,1013.04,1013.37,1013.98,-

In [79]:
pressure = pd.melt(all_province,               # pd.melt เปลี่ยนจาก wide format เป็น long format
id_vars=['จังหวัด','สถานี','เดือน','ปี'], # id_vars : column ที่ต้องการฟิคไว้ไม่ให้ melt  
                 var_name='วันที่', value_name='ความกด')

In [80]:
pressure

      จังหวัด                     สถานี  เดือน    ปี วันที่   ความกด
0         เลย  352201-หนองคาย จ.หนองคาย     10  2011      1  1005.12
1         เลย  352201-หนองคาย จ.หนองคาย     11  2011      1  1012.09
2         เลย  352201-หนองคาย จ.หนองคาย     12  2011      1  1010.43
3         เลย  352201-หนองคาย จ.หนองคาย      1  2012      1  1015.42
4         เลย  352201-หนองคาย จ.หนองคาย      2  2012      1  1013.19
...       ...                       ...    ...   ...    ...      ...
8520  ขอนแก่น  352201-หนองคาย จ.หนองคาย     10  2021     31  1012.96
8521  ขอนแก่น  352201-หนองคาย จ.หนองคาย     11  2021     31        -
8522  ขอนแก่น  352201-หนองคาย จ.หนองคาย     12  2021     31  1018.39
8523  ขอนแก่น  352201-หนองคาย จ.หนองคาย      1  2022     31  1008.91
8524  ขอนแก่น  352201-หนองคาย จ.หนองคาย      2  2022     31        -

[8525 rows x 6 columns]

In [81]:
pressure['วันที่'] = pressure['วันที่'].astype(int) # .astype('ชนิดของข้อมูลที่ต้องการ') -> แปลงชนิดของข้อมูล

In [82]:
pressure = pressure.sort_values(by=['จังหวัด','ปี','เดือน','วันที่']) # sort_values เรียงวันที่
pressure.head(5)

      จังหวัด                     สถานี  เดือน    ปี  วันที่   ความกด
220   ขอนแก่น  352201-หนองคาย จ.หนองคาย     10  2011       1  1005.47
495   ขอนแก่น  352201-หนองคาย จ.หนองคาย     10  2011       2  1006.65
770   ขอนแก่น  352201-หนองคาย จ.หนองคาย     10  2011       3  1007.49
1045  ขอนแก่น  352201-หนองคาย จ.หนองคาย     10  2011       4  1008.28
1320  ขอนแก่น  352201-หนองคาย จ.หนองคาย     10  2011       5  1009.88

# ความชื้น

## เลย

In [83]:
humidity_lei = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ความชื้นสัมพัทธ์(เปอร์เซ็นต์)/จ.เลย.xlsx',skiprows=3).drop(0, axis=0)
humidity_lei.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
humidity_lei['จังหวัด'] = 'เลย'
humidity_lei['เดือน'] =humidity_lei['เดือน/ปี'].dt.month
humidity_lei['ปี'] = humidity_lei['เดือน/ปี'].dt.year
hum_lei = humidity_lei[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## สกลนคร

In [84]:
humidity_skn = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ความชื้นสัมพัทธ์(เปอร์เซ็นต์)/จ.สกลนคร.xlsx',skiprows=3).drop(0, axis=0)
humidity_skn.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
humidity_skn['จังหวัด'] = 'สกลนคร'
humidity_skn['เดือน'] =humidity_skn['เดือน/ปี'].dt.month
humidity_skn['ปี'] = humidity_skn['เดือน/ปี'].dt.year
hum_skn = humidity_skn[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## หนองคาย

In [85]:
humidity_nki = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ความชื้นสัมพัทธ์(เปอร์เซ็นต์)/จ.หนองคาย.xlsx',skiprows=3).drop(0, axis=0)
humidity_nki.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
humidity_nki['จังหวัด'] = 'หนองคาย'
humidity_nki['เดือน'] =humidity_nki['เดือน/ปี'].dt.month
humidity_nki['ปี'] = humidity_nki['เดือน/ปี'].dt.year
hum_nk = humidity_nki[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## นครพนม

In [86]:
humidity_npm = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ความชื้นสัมพัทธ์(เปอร์เซ็นต์)/จ.นครพนม.xlsx',skiprows=3).drop(0, axis=0)
humidity_npm.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
humidity_npm['จังหวัด'] = 'นครพนม'
humidity_npm['เดือน'] = humidity_npm['เดือน/ปี'].dt.month
humidity_npm['ปี'] = humidity_npm['เดือน/ปี'].dt.year
hum_npm = pressure_npm[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## หนองคาย

In [87]:
humidity_nki = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ความชื้นสัมพัทธ์(เปอร์เซ็นต์)/จ.หนองคาย.xlsx',skiprows=3).drop(0, axis=0)
humidity_nki.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
humidity_nki['จังหวัด'] = 'หนองคาย'
humidity_nki['เดือน'] =humidity_nki['เดือน/ปี'].dt.month
humidity_nki['ปี'] = humidity_nki['เดือน/ปี'].dt.year
hum_nk = humidity_nki[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## ขอนแก่น

In [88]:
humidity_kkn = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ความชื้นสัมพัทธ์(เปอร์เซ็นต์)/จ.ขอนแก่น.xlsx',skiprows=3).drop(0, axis=0)
humidity_kkn.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
humidity_kkn['จังหวัด'] = 'ขอนแก่น'
humidity_kkn['เดือน'] = humidity_kkn['เดือน/ปี'].dt.month
humidity_kkn['ปี'] =humidity_kkn['เดือน/ปี'].dt.year
hum_kn = humidity_kkn[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## รวมตารางความชื้น ทั้ง 5 จังหวัด

In [89]:
all_province_hum = pd.concat([hum_lei, hum_skn, hum_npm, hum_nk, hum_kn])

In [90]:
humidity = pd.melt(all_province_hum,
        id_vars=['จังหวัด','สถานี','เดือน','ปี'],
                 var_name='วันที่', value_name='ความชื้น')

In [91]:
humidity['วันที่'] = humidity['วันที่'].astype(int)

In [92]:
humidity = humidity.sort_values(by=['จังหวัด','ปี','เดือน','วันที่'])

# อุณหภูมิตุ้มแห้ง

## เลย

In [93]:
dry_lei = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/อุณหภูมิตุ้มแห้ง(เซลเซียส)/จ.เลย.xlsx',skiprows=3).drop(0, axis=0)
dry_lei.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
dry_lei['จังหวัด'] = 'เลย'
dry_lei['เดือน'] =dry_lei['เดือน/ปี'].dt.month
dry_lei['ปี'] = dry_lei['เดือน/ปี'].dt.year
dryw_lei = dry_lei[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## สกลนคร

In [94]:
dry_skn = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/อุณหภูมิตุ้มแห้ง(เซลเซียส)/จ.สกล.xlsx',skiprows=3).drop(0, axis=0)
dry_skn.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
dry_skn['จังหวัด'] = 'สกลนคร'
dry_skn['เดือน'] = dry_skn['เดือน/ปี'].dt.month
dry_skn['ปี'] = dry_skn['เดือน/ปี'].dt.year
dryw_skn = dry_skn[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## นครพนม

In [95]:
dry_npm = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/อุณหภูมิตุ้มแห้ง(เซลเซียส)/จ.นครพนม.xlsx',skiprows=3).drop(0, axis=0)
dry_npm.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
dry_npm['จังหวัด'] = 'นครพนม'
dry_npm['เดือน'] = dry_npm['เดือน/ปี'].dt.month
dry_npm['ปี'] = dry_npm['เดือน/ปี'].dt.year
dryw_npm = dry_npm[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## หนองคาย

In [96]:
dry_nki = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/อุณหภูมิตุ้มแห้ง(เซลเซียส)/จ.หนองคาย.xlsx',skiprows=3).drop(0, axis=0)
dry_nki.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
dry_nki['จังหวัด'] = 'หนองคาย'
dry_nki['เดือน'] =dry_nki['เดือน/ปี'].dt.month
dry_nki['ปี'] = dry_nki['เดือน/ปี'].dt.year
dryw_nk =dry_nki[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## ขอนแก่น

In [97]:
dry_kkn = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/อุณหภูมิตุ้มแห้ง(เซลเซียส)/จ.ขอนแก่น.xlsx',skiprows=3).drop(0, axis=0)
dry_kkn.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
dry_kkn['จังหวัด'] = 'ขอนแก่น'
dry_kkn['เดือน'] = dry_kkn['เดือน/ปี'].dt.month
dry_kkn['ปี'] = dry_kkn['เดือน/ปี'].dt.year
dryw_kn = dry_kkn[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

In [155]:
dryw_kn

,จังหวัด,สถานี,เดือน,ปี,1,2,3,4,5,6,...,22,23,24,25,26,27,28,29,30,31
1,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,10,2011,27.6,25.6,25.6,25.8,24.3,24.0,...,26.5,26.7,27.6,27.4,27.2,27.3,26.9,26.3,25.8,26.2
2,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,11,2011,26.3,26.3,26.3,26.6,26.8,27.5,...,26.7,26.5,23.9,24.4,25.5,26.1,26.2,26,26,-
3,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,12,2011,25.4,23.9,21.3,22.3,23.0,25.6,...,23.9,23.6,21.1,18.3,18.3,20.4,23.5,23.7,24.2,24.1
4,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,1,2012,23.8,24.5,25.0,24.8,22.8,23.4,...,27.1,25.3,24.4,24.1,22.1,24.6,26.3,25.6,25.3,23
5,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,2,2012,23.9,25.4,25.3,24.8,27.2,28.2,...,26.9,28.3,29.1,29.6,29.2,28.2,27.5,28.5,-,-
6,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,10,2012,26.8,27.4,28.3,27.9,27.4,27.3,...,27.6,27.6,27.9,27.8,27.6,27.8,28.8,29,28.3,27.5
7,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,11,2012,25.6,26.0,26.7,27.5,28.2,28.4,...,29.5,30.0,26.8,26.0,28.2,27.9,27.2,27.5,28,-
8,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,12,2012,28.5,28.6,28.1,26.9,28.0,25.0,...,27.0,24.8,21.7,22.9,25.3,26.5,26.5,26.9,25.3,20.4
9,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,1,2013,20.8,23.9,24.9,23.5,23.8,24.3,...,25.8,26.1,26.3,26.3,25.4,25.1,20.1,23.2,24.1,24.1
10,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,2,2013,24.7,25.0,24.9,26.8,27.8,28.2,...,26.0,24.6,26.0,28.0,29.7,31.0,31.0,-,-,-
11,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,10,2013,26.1,26.8,27.9,27.5,27.3,27.1,...,26.7,26.6,26.3,23.8,24.4,24.6,25.1,26.1,27.1,27.9
12,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,11,2013,27.3,26.9,26.3,25.7,26.0,26.6,...,26.1,26.7,27.8,27.3,26.1,27.3,26.2,23,22.8,-
13,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,12,2013,23.1,21.1,21.8,23.0,23.7,23.3,...,18.3,19.6,20.6,19.0,18.6,18.2,17.9,18.6,19.1,19.4
14,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,1,2014,19.7,21.7,23.7,23.4,22.0,23.3,...,17.9,17.3,18.9,20.7,22.4,22.8,23.4,23.7,23.8,23.3
15,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,2,2014,24.5,26.2,26.8,26.5,27.0,27.9,...,25.4,26.6,27.0,28.6,29.0,28.9,29.6,-,-,-
16,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,10,2014,26.7,28.1,28.3,28.6,28.2,26.4,...,28.1,27.6,25.6,27.3,27.7,28.2,27.4,27.4,27.7,28.1
17,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,11,2014,28.5,28.7,27.5,26.2,27.0,27.3,...,25.4,26.1,26.4,26.3,27.4,27.8,28.1,28.7,29.1,-
18,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,12,2014,26.6,26.1,25.8,26.3,24.3,24.9,...,20.0,20.3,22.3,24.6,26.5,26.4,24.8,21.4,21,21.5
19,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,1,2015,20.6,20.4,21.3,22.9,25.2,26.1,...,22.9,22.6,24.3,25.0,25.1,25.6,25.9,26,25.2,24.2
20,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,2,2015,24.2,24.2,24.4,24.5,23.8,22.0,...,25.6,25.0,27.9,28.8,28.7,29.0,30.3,-,-,-
21,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,10,2015,27.2,26.7,27.0,26.8,26.2,26.3,...,27.5,27.6,26.8,26.5,27.6,28.5,28.0,27.8,28.1,28.1
22,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,11,2015,26.7,25.5,26.2,27.2,27.8,26.4,...,27.4,26.9,27.7,27.5,26.0,25.2,25.9,26.6,27.2,-
23,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,12,2015,27.8,28.8,27.9,27.7,25.1,24.7,...,25.8,27.3,28.3,28.7,25.5,25.8,25.9,25.2,25.4,24.2
24,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,1,2016,23.2,24.0,24.3,25.2,25.9,25.8,...,28.7,27.0,15.2,12.5,13.4,17.8,21.9,24.9,26.7,27.2
25,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,2,2016,27.4,22.9,21.5,23.6,24.0,20.6,...,26.6,29.1,26.2,22.4,22.4,22.8,24.4,24.5,-,-
26,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,10,2016,26.0,27.5,28.4,28.6,26.9,25.2,...,28.8,27.5,26.7,26.5,28.2,27.3,27.8,27.3,27.2,27.6
27,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,11,2016,26.5,26.3,25.2,25.3,25.7,27.0,...,28.1,28.5,27.7,27.0,26.6,24.3,23.4,24.1,24.5,-
28,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,12,2016,23.5,23.9,24.7,25.4,24.9,24.8,...,26.6,25.8,26.0,26.9,26.3,24.8,21.2,20.7,21.3,21.8
29,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,1,2017,23.3,25.7,25.6,24.2,25.8,25.6,...,23.7,22.5,23.3,24.9,25.1,23.5,23.8,23.5,25.3,24
30,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,2,2017,24.7,24.7,25.2,26.6,26.2,25.9,...,29.2,30.3,29.8,25.2,22.7,23.8,25.0,-,-,-
31,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,10,2017,27.8,27.3,26.4,25.3,26.4,27.0,...,28.2,27.4,25.8,26.3,26.8,26.8,26.5,26.3,25,24.1
32,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,11,2017,24.2,25.6,25.0,24.3,22.7,23.7,...,25.3,25.2,22.8,22.8,24.1,24.1,25.3,26.5,26.5,-
33,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,12,2017,25.7,25.3,25.0,25.9,24.8,23.9,...,21.1,24.1,24.3,21.2,19.6,19.5,22.7,24.9,25.2,23.4
34,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,1,2018,22.6,23.2,24.7,25.3,26.3,26.7,...,26.4,26.3,25.7,25.7,26.6,26.6,27.5,27.5,21.6,22.4
35,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,2,2018,18.5,20.3,19.4,19.4,19.7,17.4,...,24.8,24.2,25.9,28.2,26.3,25.3,28.1,-,-,-
36,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,10,2018,28.3,27.4,27.8,27.4,27.5,27.5,...,27.0,28.1,27.6,28.3,28.4,28.1,27.1,27.3,26.5,25
37,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,11,2018,24.3,23.6,24.1,24.9,25.9,27.1,...,28.4,25.4,25.5,25.7,25.0,23.4,23.3,25.9,27.2,-
38,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,12,2018,27.8,27.9,28.5,27.9,27.9,28.0,...,28.9,27.3,26.3,25.6,26.0,25.9,26.3,24.1,23.8,21.7
39,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,1,2019,21.3,21.4,22.7,23.6,25.2,26.3,...,24.0,23.4,24.0,25.1,24.3,23.7,23.8,24.8,26,26.9
40,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,2,2019,26.5,26.1,28.2,28.6,29.1,29.4,...,30.2,30.0,30.3,30.2,28.2,27.8,29.4,-,-,-
41,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,10,2019,29.3,29.8,29.8,27.9,26.7,27.3,...,29.1,30.0,30.1,29.6,29.1,29.2,29.2,28.2,26,25.3
42,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,11,2019,24.6,27.1,27.5,27.0,27.0,26.4,...,26.1,26.2,26.4,26.4,26.4,27.7,27.3,26,26.7,-
43,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,12,2019,27.5,25.3,21.7,20.6,20.0,19.7,...,26.7,27.6,27.2,26.8,26.4,25.7,24.6,25,25.9,26.3
44,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,1,2020,26.4,26.5,26.5,26.3,26.0,25.9,...,27.7,28.9,28.5,28.1,27.7,23.9,23.9,24.2,21.8,21.6
45,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,2,2020,23.6,25.0,26.5,26.5,25.7,26.1,...,25.5,25.4,25.8,26.9,26.6,26.3,26.6,27.8,-,-
46,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,10,2020,26.5,28.2,28.0,28.6,27.1,27.8,...,24.9,24.6,23.9,25.3,23.0,25.1,26.0,23.4,26,26.1
47,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,11,2020,27.1,26.8,26.7,25.2,25.6,25.8,...,28.1,27.4,26.8,26.6,26.2,25.7,25.4,24.4,23.7,-
48,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,12,2020,23.6,24.7,23.8,21.6,21.0,21.1,...,20.4,21.7,24.1,24.5,25.0,26.8,26.7,27.2,24.9,19
49,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,1,2021,18.1,17.8,21.0,22.2,24.0,24.3,...,22.6,23.5,25.2,26.1,25.7,25.6,25.2,23.5,22.7,24.2
50,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,2,2021,25.0,25.8,25.3,25.1,24.8,24.7,...,26.8,26.9,27.8,28.7,29.3,29.2,28.3,-,-,-
51,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,10,2021,28.8,28.9,27.4,28.8,28.7,27.2,...,27.1,24.5,24.8,25.6,25.6,26.4,24.2,26.4,27.7,27.5
52,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,11,2021,27.5,27.6,27.3,27.5,28.1,28.1,...,27.6,25.1,23.9,24.5,23.9,23.8,23.6,24.3,24,-
53,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,12,2021,22.8,21.7,20.7,20.5,20.9,21.7,...,24.6,24.0,25.2,25.0,25.5,24.7,23.3,25,24.8,23.3
54,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,1,2022,23.4,23.4,24.0,23.7,24.1,24.7,...,23.7,22.7,25.1,26.0,26.6,26.3,26.4,27.8,27.8,26.9
55,ขอนแก่น,381201-ขอนแก่น จ.ขอนแก่น,2,2022,25.3,24.9,25.5,21.6,22.3,23.2,...,20.6,21.3,21.1,21.4,23.2,25.1,25.9,-,-,-

## รวมตารางอุณหภูมิตุ้มแห้ง ทั้ง 5 จังหวัด

In [98]:
all_province_dry = pd.concat([dryw_lei, dryw_skn, dryw_npm, dryw_nk, dryw_kn])

In [99]:
dry_buld = pd.melt(all_province_dry,
        id_vars=['จังหวัด','สถานี','เดือน','ปี'],
                 var_name='วันที่', value_name='อุณหภูมิตุ้มแห้ง')

In [100]:
dry_buld['วันที่'] = dry_buld['วันที่'].astype(int)

In [101]:
dry_buld = dry_buld.sort_values(by=['จังหวัด','ปี','เดือน','วันที่'])

# อุณหภูมิจุดน้ำค้าง

## เลย

In [102]:
dew_lei = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/อุณหภูมิจุดน้ำค้าง(เซลเซียส)/จ.เลย.xlsx',skiprows=3).drop(0, axis=0)
dew_lei.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
dew_lei['จังหวัด'] = 'เลย'
dew_lei['เดือน'] =dew_lei['เดือน/ปี'].dt.month
dew_lei['ปี'] = dew_lei['เดือน/ปี'].dt.year
dewp_lei = dew_lei[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## สกลนคร

In [103]:
dew_skn = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/อุณหภูมิจุดน้ำค้าง(เซลเซียส)/จ.สกล.xlsx',skiprows=3).drop(0, axis=0)
dew_skn.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
dew_skn['จังหวัด'] = 'สกลนคร'
dew_skn['เดือน'] = dew_skn['เดือน/ปี'].dt.month
dew_skn['ปี'] = dew_skn['เดือน/ปี'].dt.year
dewp_skn = dew_skn[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## นครพนม

In [104]:
dew_npm = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/อุณหภูมิจุดน้ำค้าง(เซลเซียส)/จ.นครพนม.xlsx',skiprows=3).drop(0, axis=0)
dew_npm.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
dew_npm['จังหวัด'] = 'นครพนม'
dew_npm['เดือน'] = dew_npm['เดือน/ปี'].dt.month
dew_npm['ปี'] = dew_npm['เดือน/ปี'].dt.year
dewp_npm = dew_npm[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## หนองคาย

In [105]:
dew_nki = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/อุณหภูมิจุดน้ำค้าง(เซลเซียส)/จ.หนองคาย.xlsx',skiprows=3).drop(0, axis=0)
dew_nki.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
dew_nki['จังหวัด'] = 'หนองคาย'
dew_nki['เดือน'] =dew_nki['เดือน/ปี'].dt.month
dew_nki['ปี'] = dew_nki['เดือน/ปี'].dt.year
dewp_nk =dew_nki[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## ขอนแก่น

In [106]:
dew_kkn = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/อุณหภูมิจุดน้ำค้าง(เซลเซียส)/จ.ขอนแก่น.xlsx',skiprows=3).drop(0, axis=0)
dew_kkn.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
dew_kkn['จังหวัด'] = 'ขอนแก่น'
dew_kkn['เดือน'] = dew_kkn['เดือน/ปี'].dt.month
dew_kkn['ปี'] = dew_kkn['เดือน/ปี'].dt.year
dewp_kn = dew_kkn[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## รวมตารางอุณหภูมิจุดน้ำค้าง ทั้ง 5 จังหวัด

In [107]:
all_province_dew = pd.concat([dewp_lei, dewp_skn, dewp_npm, dewp_nk, dewp_kn])

In [108]:
dew_point = pd.melt(all_province_dew,
        id_vars=['จังหวัด','สถานี','เดือน','ปี'],
                 var_name='วันที่', value_name='อุณหภูมิจุดน้ำค้าง')

In [109]:
dew_point['วันที่'] = dew_point['วันที่'].astype(int)

In [110]:
dew_point =dew_point.sort_values(by=['จังหวัด','ปี','เดือน','วันที่'])

 # อุณหภูมิต่ำสุด

## เลย

In [111]:
low_lei = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/อุณหภูมิต่ำสุด(เซลเซียส)/จ.เลย.xlsx',skiprows=3).drop(0, axis=0)
low_lei.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
low_lei['จังหวัด'] = 'เลย'
low_lei['เดือน'] =low_lei['เดือน/ปี'].dt.month
low_lei['ปี'] = low_lei['เดือน/ปี'].dt.year
lowt_lei = low_lei[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

,จังหวัด,สถานี,เดือน,ปี,1,2,3,4,5,6,...,22,23,24,25,26,27,28,29,30,31
1,เลย,353201-เลย จ.เลย,10,2011,23.5,24.3,22.5,23.0,22.7,23.2,...,21.0,20.9,21.5,21.6,21.8,21.5,21.2,21.8,21,20.5
2,เลย,353201-เลย จ.เลย,11,2011,20.7,19.9,19.1,19.0,19.5,19.8,...,20.5,21.7,18.6,16.9,17.0,19.2,19.3,20.3,19.5,-
3,เลย,353201-เลย จ.เลย,12,2011,18,19.6,15.5,14.4,17.1,15.5,...,15.0,16.9,15.0,11.1,9.9,10.0,13,15.9,16.5,16.4

## สกลนคร

In [112]:
low_skn = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/อุณหภูมิต่ำสุด(เซลเซียส)/จ.สกล.xlsx',skiprows=3).drop(0, axis=0)
low_skn.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
low_skn['จังหวัด'] = 'สกลนคร'
low_skn['เดือน'] = low_skn['เดือน/ปี'].dt.month
low_skn['ปี'] = low_skn['เดือน/ปี'].dt.year
lowt_skn = low_skn[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## นครพนม

In [113]:
low_npm = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/อุณหภูมิต่ำสุด(เซลเซียส)/จ.นครพนม.xlsx',skiprows=3).drop(0, axis=0)
low_npm.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
low_npm['จังหวัด'] = 'นครพนม'
low_npm['เดือน'] = low_npm['เดือน/ปี'].dt.month
low_npm['ปี'] = low_npm['เดือน/ปี'].dt.year
lowt_npm = low_npm[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## หนองคาย

In [114]:
low_nki = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/อุณหภูมิต่ำสุด(เซลเซียส)/จ.หนองคาย.xlsx',skiprows=3).drop(0, axis=0)
low_nki.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
low_nki['จังหวัด'] = 'หนองคาย'
low_nki['เดือน'] = low_nki['เดือน/ปี'].dt.month
low_nki['ปี'] = low_nki['เดือน/ปี'].dt.year
lowt_nk =low_nki[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## ขอนแก่น

In [115]:
low_kkn = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/อุณหภูมิต่ำสุด(เซลเซียส)/จ.ขอนแก่น.xlsx',skiprows=3).drop(0, axis=0)
low_kkn.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
low_kkn['จังหวัด'] = 'ขอนแก่น'
low_kkn['เดือน'] = low_kkn['เดือน/ปี'].dt.month
low_kkn['ปี'] = low_kkn['เดือน/ปี'].dt.year
lowt_kn = low_kkn[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## รวมตารางอุณหภูมิต่ำสุด ทั้ง 5 จังหวัด

In [116]:
all_province_low = pd.concat([lowt_lei, lowt_skn, lowt_npm, lowt_nk, lowt_kn])

In [117]:
mini_temp = pd.melt(all_province_low,
        id_vars=['จังหวัด','สถานี','เดือน','ปี'],
                 var_name='วันที่', value_name='อุณหภูมิต่ำสุด')

In [118]:
mini_temp['วันที่'] = mini_temp['วันที่'].astype(int)

In [119]:
mini_temp = mini_temp.sort_values(by=['จังหวัด','ปี','เดือน','วันที่'])

# จำนวนเมฆ

## เลย

In [120]:
clound_lei = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/จำนวนเมฆ(10ส่วน)/จ.เลย.xlsx',skiprows=3).drop(0, axis=0)
clound_lei.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
clound_lei['จังหวัด'] = 'เลย'
clound_lei['เดือน'] =clound_lei['เดือน/ปี'].dt.month
clound_lei['ปี'] = clound_lei['เดือน/ปี'].dt.year
clounda_lei = clound_lei[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## สกลนคร

In [121]:
clound_skn = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/จำนวนเมฆ(10ส่วน)/จ.สกลนคร.xlsx',skiprows=3).drop(0, axis=0)
clound_skn.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
clound_skn['จังหวัด'] = 'สกลนคร'
clound_skn['เดือน'] = clound_skn['เดือน/ปี'].dt.month
clound_skn['ปี'] = clound_skn['เดือน/ปี'].dt.year
clounda_skn = clound_skn[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## นครพนม

In [122]:
clound_npm = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/จำนวนเมฆ(10ส่วน)/จ.นครพนม.xlsx',skiprows=3).drop(0, axis=0)
clound_npm.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
clound_npm['จังหวัด'] = 'นครพนม'
clound_npm['เดือน'] = clound_npm['เดือน/ปี'].dt.month
clound_npm['ปี'] = clound_npm['เดือน/ปี'].dt.year
clounda_npm = clound_npm[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## หนองคาย

In [123]:
clound_nki = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/จำนวนเมฆ(10ส่วน)/จ.หนองคาย.xlsx',skiprows=3).drop(0, axis=0)
clound_nki.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
clound_nki['จังหวัด'] = 'หนองคาย'
clound_nki['เดือน'] =clound_nki['เดือน/ปี'].dt.month
clound_nki['ปี'] = clound_nki['เดือน/ปี'].dt.year
clounda_nk = clound_nki[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## ขอนแก่น

In [124]:
clound_kkn = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/จำนวนเมฆ(10ส่วน)/จ.ขอนแก่น.xlsx',skiprows=3).drop(0, axis=0)
clound_kkn.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
clound_kkn['จังหวัด'] = 'ขอนแก่น'
clound_kkn['เดือน'] = clound_kkn['เดือน/ปี'].dt.month
clound_kkn['ปี'] = clound_kkn['เดือน/ปี'].dt.year
clounda_kn = clound_kkn[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## รวมตารางจำนวนเมฆ ทั้ง 5 จังหวัด

In [125]:
all_province_clound = pd.concat([clounda_lei,clounda_skn, clounda_npm, clounda_nk, clounda_kn])

In [126]:
clound = pd.melt(all_province_clound,
        id_vars=['จังหวัด','สถานี','เดือน','ปี'],
                 var_name='วันที่', value_name='จำนวนเมฆ')

In [127]:
clound['วันที่'] = clound['วันที่'].astype(int)

In [128]:
clound = clound.sort_values(by=['จังหวัด','ปี','เดือน','วันที่'])

#  ปริมาณฝน

## เลย

In [129]:
rain_lei = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ปริมาณฝน(มิลลิเมตร)/จ.เลย.xlsx',skiprows=3).drop(0, axis=0)
rain_lei.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
rain_lei['จังหวัด'] = 'เลย'
rain_lei['เดือน'] =rain_lei['เดือน/ปี'].dt.month
rain_lei['ปี'] = rain_lei['เดือน/ปี'].dt.year
raina_lei = rain_lei[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## สกลนคร

In [130]:
rain_skn = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ปริมาณฝน(มิลลิเมตร)/จ.สกล.xlsx',skiprows=3).drop(0, axis=0)
rain_skn.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
rain_skn['จังหวัด'] = 'สกลนคร'
rain_skn['เดือน'] = rain_skn['เดือน/ปี'].dt.month
rain_skn['ปี'] = rain_skn['เดือน/ปี'].dt.year
raina_skn = rain_skn[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## นครพนม

In [131]:
rain_npm = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ปริมาณฝน(มิลลิเมตร)/จ.นครพนม.xlsx',skiprows=3).drop(0, axis=0)
rain_npm.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
rain_npm['จังหวัด'] = 'นครพนม'
rain_npm['เดือน'] = rain_npm['เดือน/ปี'].dt.month
rain_npm['ปี'] = rain_npm['เดือน/ปี'].dt.year
raina_npm =rain_npm[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## หนองคาย

In [132]:
rain_nki = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ปริมาณฝน(มิลลิเมตร)/จ.หนองคาย.xlsx',skiprows=3).drop(0, axis=0)
rain_nki.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
rain_nki['จังหวัด'] = 'หนองคาย'
rain_nki['เดือน'] = rain_nki['เดือน/ปี'].dt.month
rain_nki['ปี'] = rain_nki['เดือน/ปี'].dt.year
raina_nk = rain_nki[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## ขอนแก่น

In [133]:
rain_kkn = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ปริมาณฝน(มิลลิเมตร)/จ.ขอนแก่น.xlsx',skiprows=3).drop(0, axis=0)
rain_kkn.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
rain_kkn['จังหวัด'] = 'ขอนแก่น'
rain_kkn['เดือน'] = rain_kkn['เดือน/ปี'].dt.month
rain_kkn['ปี'] = rain_kkn['เดือน/ปี'].dt.year
raina_kn = rain_kkn[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## รวมตารางปริมาณฝน ทั้ง 5 จังหวัด

In [134]:
all_province_rain = pd.concat([raina_lei,raina_skn, raina_npm, raina_nk, raina_kn])

In [135]:
rain = pd.melt(all_province_rain,
        id_vars=['จังหวัด','สถานี','เดือน','ปี'],
                 var_name='วันที่', value_name='ปริมาณฝน')

In [136]:
rain['วันที่'] = rain['วันที่'].astype(int)

In [137]:
rain =rain.sort_values(by=['จังหวัด','ปี','เดือน','วันที่'])

# ความเร็วลม

## เลย

In [138]:
wind_lei = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ความเร็วลม(นอต)/จ.เลย.xlsx',skiprows=3).drop(0, axis=0)
wind_lei.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
wind_lei['จังหวัด'] = 'เลย'
wind_lei['เดือน'] =wind_lei['เดือน/ปี'].dt.month
wind_lei['ปี'] = wind_lei['เดือน/ปี'].dt.year
winds_lei = wind_lei[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## สกลนคร

In [139]:
wind_skn = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ความเร็วลม(นอต)/จ.สกลนคร.xlsx',skiprows=3).drop(0, axis=0)
wind_skn.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
wind_skn['จังหวัด'] = 'สกลนคร'
wind_skn['เดือน'] = wind_skn['เดือน/ปี'].dt.month
wind_skn['ปี'] = wind_skn['เดือน/ปี'].dt.year
winds_skn = wind_skn[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## นครพนม

In [140]:
wind_npm = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ความเร็วลม(นอต)/จ.นครพนม.xlsx',skiprows=3).drop(0, axis=0)
wind_npm.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
wind_npm['จังหวัด'] = 'นครพนม'
wind_npm['เดือน'] = wind_npm['เดือน/ปี'].dt.month
wind_npm['ปี'] = wind_npm['เดือน/ปี'].dt.year
winds_npm = wind_npm[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## หนองคาย

In [141]:
wind_nki = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ความเร็วลม(นอต)/จ.หนองคาย.xlsx',skiprows=3).drop(0, axis=0)
wind_nki.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
wind_nki['จังหวัด'] = 'หนองคาย'
wind_nki['เดือน'] =wind_nki['เดือน/ปี'].dt.month
wind_nki['ปี'] = wind_nki['เดือน/ปี'].dt.year
winds_nk = wind_nki[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## ขอนแก่น

In [142]:
wind_kkn = pd.read_excel('/content/drive/MyDrive/bsc_DPDM_data/อุตุ/ความเร็วลม(นอต)/จ.ขอนแก่น.xlsx',skiprows=3).drop(0, axis=0)
wind_kkn.columns.values[3:34] =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
wind_kkn['จังหวัด'] = 'ขอนแก่น'
wind_kkn['เดือน'] = wind_kkn['เดือน/ปี'].dt.month
wind_kkn['ปี'] = wind_kkn['เดือน/ปี'].dt.year
winds_kn = wind_kkn[['จังหวัด','สถานี','เดือน','ปี','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']]

## รวมตารางความเร็วลม ทั้ง 5 จังหวัด

In [143]:
all_province_wind = pd.concat([winds_lei, winds_skn, winds_npm, winds_nk, winds_kn])

In [144]:
wind = pd.melt(all_province_wind,
        id_vars=['จังหวัด','สถานี','เดือน','ปี'],
                 var_name='วันที่', value_name='ความเร็วลม')

In [145]:
wind['วันที่'] = wind['วันที่'].astype(int)

In [146]:
wind = wind.sort_values(by=['จังหวัด','ปี','เดือน','วันที่'])

# รวมตารางทั้งหมด

In [147]:
total = pd.concat([pressure,humidity,dry_buld,dew_point,mini_temp,clound,rain,wind], axis=1)

In [148]:
total.columns.duplicated() # True : column ที่ซ้ำ

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False])

In [149]:
total = total.loc[:, ~total.columns.duplicated()]

In [150]:
final = total.sort_values(by=['จังหวัด','ปี','เดือน','วันที่']).drop(total.index[(total['ความกด'] == '-')],axis=0)
final

,จังหวัด,สถานี,เดือน,ปี,วันที่,ความกด,ความชื้น,อุณหภูมิตุ้มแห้ง,อุณหภูมิจุดน้ำค้าง,อุณหภูมิต่ำสุด,จำนวนเมฆ,ปริมาณฝน,ความเร็วลม
220,ขอนแก่น,352201-หนองคาย จ.หนองคาย,10,2011,1,1005.47,83.0,26.8,21.3,24.8,9,1.4,3
495,ขอนแก่น,352201-หนองคาย จ.หนองคาย,10,2011,2,1006.65,92.0,26.8,23.8,23.0,10,17.7,2
770,ขอนแก่น,352201-หนองคาย จ.หนองคาย,10,2011,3,1007.49,86.0,28.3,22.4,22.1,10,3,3
1045,ขอนแก่น,352201-หนองคาย จ.หนองคาย,10,2011,4,1008.28,80.0,26.8,24.2,22.8,8,0,2
1320,ขอนแก่น,352201-หนองคาย จ.หนองคาย,10,2011,5,1009.88,86.0,26.9,24.1,23.1,10,2.2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6379,เลย,352201-หนองคาย จ.หนองคาย,2,2022,24,1018.88,74.0,25.0,15.3,14.0,-,0,2
6654,เลย,352201-หนองคาย จ.หนองคาย,2,2022,25,1017.8,74.0,28.1,19.9,12.8,1,0,1
6929,เลย,352201-หนองคาย จ.หนองคาย,2,2022,26,1016.54,74.0,28.8,19.4,13.5,0,0,1
7204,เลย,352201-หนองคาย จ.หนองคาย,2,2022,27,1014.97,74.0,22.3,13.9,15.0,3,0,1
7479,เลย,352201-หนองคาย จ.หนองคาย,2,2022,28,1012.88,72.0,25.0,16.3,17.6,2,0,1